### ISSUE TITLE
cannot install vidtest2

### ISSUE THREAD

**Issue by aslozhkin** [nanoscopic/ios_remote_provider#18]
![vidtesterror](https://user-images.githubusercontent.com/73738339/119462195-20791300-bd49-11eb-8f20-f35ab55718ec.jpg)
Also tried rename vidtest2 bundle id and vidtest2SetupUI bundle id

**Comment by sai-tirunagiri** [comment]
If you are finding it difficult to install the ipa through xcode please use this ipa - https://github.com/nanoscopic/ios_video_app/releases/download/v1.0/vidtest_clean.ipa - resign this ipa and install on the device.

**Comment by sai-tirunagiri** [comment]
If you are going to use the apple id to sign multiple devices say ~> 20 devices, it makes sense to purchase a developer licence also, it makes life easy when it comes to resigning the apps.

**Comment by sai-tirunagiri** [comment]
Just a suggestion, why not make use of the jpeg stream which is available on the WebDriverAgent itself, why have an app to broadcast the screen.

After we start webdriver agent runner on the device if we hit url http://192.168.1.15:9100 jpeg video stream starts.

@nanoscopic

**Comment by nanoscopic** [comment]
@sai-tirunagiri I am going to add support for using the WDA provided MJPEG stream, and have meaning to do so for a long time but simply never did.

There are a few reasons for using the app instead:
1. The app gets raw access to the image data before conversion to Jpeg. This is actually possible as well via the mechanism WDA is using ( one can fetch the UIImage / or was it the CGImag? I forget... ) This is important because of 2
2. The app compares the screen from frame to frame and only sends a frame when something on screen has changed. This saves bandwidth, especially when nothing on screen is moving or changing ( which is the majority of the time ) The cheap and easy way to compare frames is to compare a hash of the screen data, and that is what is done. Having the raw image data is necessary to do such a comparison by hash.
3. The app jpeg compression code is highly optimized to use hardware accelerated image resizing and compression. As a result the frame rate can be better/higher than how WDA is doing this.
4. The app is using NNG to send frames. This is more resilient to various issues than the MJPEG stream is.
5. I can actually publish the app onto the app store, making it possible to then stream the screen without even having a developer account. This is a small benefit because for CF everyone will need an account to run WDA, but there are use cases for this.

Why one may prefer WDA MJPEG over the app:
1. To avoid having to start the video app stream
2. For quick debugging ( just visit the stream url in browser ) I will, though, add such a feature to the app as well.

**Comment by nanoscopic** [comment]
As said above the way to resolve the declared issue is to configure bundle id to be different. Once configured in the config.json file, building with the Makefile with automatically adjust the project bundle id and built a proper vidtest xcarchive.

So... either do that, or get a paid developer account.
