### ISSUE TITLE
Error "Process end - wda" when using 2 devices

### ISSUE THREAD

**Issue by Slavaleriya** [nanoscopic/ios_remote_provider#21]
Hello, please tell me a question about the number of simultaneously connected devices to your project. Is it really possible to connect only 1 iPhone to 1 MacBook, or is it not?

**Comment by nanoscopic** [comment]
Not sure why you believe it is only possible to connect a single device to a single machine running MacOS.

This project has been designed from the start to not be thus restricted.

For a time it was limited to 8 devices simultaneous per machine, due to the use of `xcodebuild` to run `WDA`. That has not been true since the change to use `go-ios` to run `WDA`, and more recently the ability to use `tidevice`.

I have only tested up to 5 devices simultaneous on a single machine so far, but there is no technical reason currently that 20 should not work. In practice there are a number of bugs that still exist that would make that problematic, but they are being worked on and will be solved.

I would, though, not recommend using MacOS in the future to run this project. It will soon be made to run on straight Linux and will perform much better there. MacOS has a lot of absurd restrictions and problems that cannot be readily solved. It is, essentially, not a server OS. Running on Linux is no longer a long term goal. It is a short term one. I'd like to be off MacOS, or at least only minimally supporting it, ASAP. MacOS causes far more problems than it is worth.

**Comment by Slavaleriya** [comment]
Thank you very much for your answer!

**Comment by Slavaleriya** [comment]
I successfully started one device but the 2 devices dont work together, I suppose due to a wda port conflict.
please help me how to run 2 devices on different wda ports

**Comment by nanoscopic** [comment]
Please:
1. Explain what happens when you connect two devices; preferably by showing some of the log output, which I'm assuming is showing an error related to why it isn't working for you.
2. Update the ticket title to something matching the issue, such as "Error [name of error] when using 2 devices"

I've used the current code for multiple devices without issue. Unless you have something else using/blocking the ports it uses to do so it will/should work.

There is no current "wda port conflict" within the code itself related to using 2 devices at once. Your question doesn't make sense as that is already accounted for by the code and the way the system works.

You'll need to provide more information about what is happening in your scenario for me to get an idea of what is going on.

**Comment by Slavaleriya** [comment]
After plug in second device i get the error "Process end - wda", the log output:
Creating IIFDev with udid=00008101-00125D080112001E
udid: 00008101-00125D080112001E
Running bin/iosif [mg -json -id 00008101-00125D080112001E AvailableDisplayZoomSizes main-screen-width main-screen-height]
json:{
"AvailableDisplayZoomSizes":{
  default:[
    3
    375
    3
    812
  ]
  zoomed:[
    3
    320
    3
    693
  ]
}
,
"main-screen-width":1080
,
"main-screen-height":2340

}

Notified control floor of 'device existence'; uuid=***001E
udid for info: 00008101-00125D080112001E
json:{
DeviceName:"iPhone (Айфон)"
,
EthernetAddress:"0c:19:f8:9d:d6:df"
,
ModelNumber:"MGE13"
,
HardwareModel:"D52gAP"
,
ProductType:"iPhone13,1"
,
ProductVersion:"14.4.2"
,
UniqueDeviceID:"00008101-00125D080112001E"
,
InternationalMobileEquipmentIdentity:"356450252412561"
,
}

mapped result:map[DeviceName:iPhone (Айфон) EthernetAddress:0c:19:f8:9d:d6:df HardwareModel:D52gAP InternationalMobileEquipmentIdentity:356450252412561 ModelNumber:MGE13 ProductType:iPhone13,1 ProductVersion:14.4.2 UniqueDeviceID:00008101-00125D080112001E]
INFO[0075] Device Info                                   info="map[DeviceName:iPhone (Айфон) EthernetAddress:0c:19:f8:9d:d6:df HardwareModel:D52gAP InternationalMobileEquipmentIdentity:356450252412561 ModelNumber:MGE13 ProductType:iPhone13,1 ProductVersion:14.4.2 UniqueDeviceID:00008101-00125D080112001E]" type=devInfo uuid="***001E"
Notified control floor of 'device info'; uuid=***001E
Starting bin/iosif with [tunnel -id 00008101-00125D080112001E 8106:8100]
port = 8109
id = 00008101-00125D080112001E
INFO[0075] Process start - tunnel_8106->8100             binary=bin/iosif proc="tunnel_8106->8100" type=proc_start
INFO[0075] Process start - backupVideo                   binary=bin/iosif id=00008101-00125D080112001E port=8109 proc=backupVideo type=proc_start
INFO[0075] Process start - wda                           binary=bin/go-ios proc=wda type=proc_start
INFO[0075] listening on tcp://127.0.0.1:8109             proc=backupVideo
listening on tcp://127.0.0.1:8109
WARN[0075] Process end - wda                             proc=wda type=proc_end
INFO[0075] Process start - wda                           binary=bin/go-ios proc=wda type=proc_start
Notified control floor of 'wda stop'; uuid=***001E
Got incoming frame 870
WARN[0075] Process end - wda                             proc=wda type=proc_end
Notified control floor of 'wda stop'; uuid=***001E
INFO[0077] Process start - wda                           binary=bin/go-ios proc=wda type=proc_start
WARN[0077] Process end - wda                             proc=wda type=proc_end
Notified control floor of 'wda stop'; uuid=***001E
Got incoming frame 900
panic: Post "http://127.0.0.1:8106/session": read tcp 127.0.0.1:49694->127.0.0.1:8106: read: connection reset by peer

goroutine 19 [running]:
main.(*WDA).create_session(0xc000310000, 0x0, 0x0, 0xc00021a570, 0xc0000d01e0)
 /Users/mcloud-ios/ios_remote_provider/wda.go:116 +0x3a5
main.(*WDA).ensureSession(0xc000310000)
 /Users/mcloud-ios/ios_remote_provider/wda.go:75 +0x3a
main.(*Device).enableVideo(0xc0002d0000)
 /Users/mcloud-ios/ios_remote_provider/device.go:267 +0x74
main.(*Device).startProcs(0xc0002d0000)
 /Users/mcloud-ios/ios_remote_provider/device.go:230 +0xd4
main.(*Device).startup(0xc0002d0000)
 /Users/mcloud-ios/ios_remote_provider/device.go:217 +0x39
main.(*DeviceTracker).onDeviceConnect1(0xc0000ce7e0, 0x4477e00, 0xc000294080, 0xc00017c5b0)
 /Users/mcloud-ios/ios_remote_provider/device_tracker.go:135 +0x5e5
main.NewDeviceTracker.func1(0x4477e00, 0xc000294080, 0xc000022260, 0x19)
 /Users/mcloud-ios/ios_remote_provider/device_tracker.go:46 +0x3e
main.(*IIFBridge).OnConnect(0xc0000a8380, 0xc000022260, 0x19, 0xc000022280, 0x13, 0xc0000ce8c0)
 /Users/mcloud-ios/ios_remote_provider/bridge_iif.go:88 +0xc8
main.(*IIFBridge).startDetect.func2(0xc000028050, 0x4c, 0xc0000ce8c0)
 /Users/mcloud-ios/ios_remote_provider/bridge_iif.go:64 +0x29a
main.proc_generic.func1(0xc0000ce8c0, 0xc000092f60, 0xc0000ca380, 0xc000092e70, 0xc000092f30, 0xc0000ec060, 0xc0000d2158, 0x0, 0x0)
/Users/mcloud-ios/ios_remote_provider/proc_generic.go:194 +0xdab
created by main.proc_generic
 /Users/mcloud-ios/ios_remote_provider/proc_generic.go:109 +0x669

**Comment by Slavaleriya** [comment]
Still get this error, using tidevice.
When plugged in one any device (iPhone 12 mini, 7, se2020) - works correctly, when plug second device - wda error. Each one iphone works fine individually.
@nanoscopic do you have any idea what may be wrong?

**Comment by chewbacca70** [comment]
Hi, I got the same Problem.

here is some of the Provider log:
Got request to start video stream for 00008030-0001111414FA402E
self signed option
Connecting to CF imgStream
Connected CF imgStream
Telling video stream to start
Got incoming frame 2070
Setting discard to false
Error creating session: Post "http://127.0.0.1:8102/session": read tcp 127.0.0.1:56733->127.0.0.1:8102: read: connection reset by peer
  Retrying
Error creating session: Post "http://127.0.0.1:8102/session": read tcp 127.0.0.1:56734->127.0.0.1:8102: read: connection reset by peer
  Retrying
Got incoming frame 2100
Got incoming frame 2130
Error creating session: Post "http://127.0.0.1:8102/session": read tcp 127.0.0.1:56735->127.0.0.1:8102: read: connection reset by peer
  Retrying
Error creating session: Post "http://127.0.0.1:8102/session": read tcp 127.0.0.1:56736->127.0.0.1:8102: read: connection reset by peer
  Retrying
Got incoming frame 2160
Error creating session: Post "http://127.0.0.1:8102/session": read tcp 127.0.0.1:56737->127.0.0.1:8102: read: connection reset by peer
  Retrying
Error creating session: Post "http://127.0.0.1:8102/session": read tcp 127.0.0.1:56738->127.0.0.1:8102: read: connection reset by peer
  Retrying
Got incoming frame 2190
Main loop stop
Main loop start
Error creating session: Post "http://127.0.0.1:8102/session": read tcp 127.0.0.1:56739->127.0.0.1:8102: read: connection reset by peer
  Retrying

**Comment by Slavaleriya** [comment]
@chewbacca70 
Did you manage to solve the problem?

**Comment by chewbacca70** [comment]
@Slavaleriya 
No unfortunately not, as soon as I start the provider with two devices connected, I still get 
Error creating session: Post "http://127.0.0.1:8102/session": read tcp 127.0.0.1:56733->127.0.0.1:8102: read: connection reset by peer
Retrying

**Comment by nanoscopic** [comment]
Corrected. Looked into this and the cause is rather simple; the calls to startup WDA were not specifying udid, either for go-ios or tidevice. I updated the code to do so and tested it with multiple devices and it works now for me without the described issues.

**Comment by chewbacca70** [comment]
@nanoscopic 
Thank you so much. It works on my machine now! 
My latest observation is that the video app wont start on the second connected device. If I start the video stream manually on the second device it works.

Cheers
Chubbi
