### ISSUE TITLE
tidevice ./main run issue

### ISSUE THREAD

**Issue by chewbacca70** [nanoscopic/ios_remote_provider#24]
Hi,
I added 
      
startMethod: "tidevice"
to my config.json file

I did 
make usetidevice

but
when ./main run I get this issue. 

Connected to control port
Attempting to connect to video
Connected to video port
Main loop start
FIRSTFRAME{"type":"frame1","width":562,"height":1000,"uuid":"dc490c9beb4c3423b1102678f57eab21d2c20fc7"}
FATA[0002] [WDA] Incorrect WDA bundle id                 port=8102 proc=wda rawErr="tidevice.exceptions.MuxError: ('No app matches', 'com.appium.WebDriverAgentRunner.xctrunner')" type=wda_start_err uuid="***0fc7"

Any idea why this happens?
BR

**Comment by nanoscopic** [comment]
Yes, it says this if you don't have WebDriverAgent installed to your device build from the repo pulled by this project.

The repo used is my fork of the Appium fork. It needs to be built and installed to your device before running the provider.

If you are using some alternative build of WebDriverAgent instead of my fork, be aware of two things:
1. Clicking won't work ( I added a faster clicking method to my fork of WDA )
2. You'll need to adjust the bundle id in config for WDA so that it knows which one to run. ( but because of 1 this doesn't accomplish much till I add an option to not use my custom click method and use a standard unchanged WDA )

**Comment by chewbacca70** [comment]
Hi @nanoscopic,
I installed WDA to my device from your repos.
But I still got the error. Any Idea of what I am doing wrong?

**Comment by chewbacca70** [comment]
Closed the Issue as I was able to install WDA now from the repo.
Maybe this could also be mentioned in the readme that it is a precondition to install WDA as I was missing it out completely.
