### ISSUE TITLE
ios_remote_provider starting returns error - StatusCode from controlfloor login:'400'

### ISSUE THREAD

**Issue by kristeedev** [nanoscopic/ios_remote_provider#3]
Hello @nanoscopic ,

I faced this error while running. Kindly help.

Started controlfloor separately and then tried to run ios_remote_provider:
ios_remote_provider $> ./main run -debug

StatusCode from controlfloor login:'400'
Could not login to control floor
link for dialer = ws://localhost:8080/provider/ws
panic: websocket: bad handshake

goroutine 1 [running]:
main.(*ControlFloor).openWebsocket(0xc00022e280)
	ios_remote_provider/controlfloor.go:155 +0x3ad
main.NewControlFloor(0xc0000b63c0, 0x42f48e9)
	ios_remote_provider/controlfloor.go:88 +0x498
main.NewDeviceTracker(0xc0000b63c0, 0xc0000b63c0)
	ios_remote_provider/device_tracker.go:35 +0x4b
main.runMain(0xc0000ba190)
	ios_remote_provider/main.go:54 +0x4c
github.com/nanoscopic/uclop/mod.(*Cmd).Run(...)
	go/pkg/mod/github.com/nanoscopic/uclop@v1.1.0/mod/main.go:164
github.com/nanoscopic/uclop/mod.(*Uclop).Run(0xc000193e50)
	go/pkg/mod/github.com/nanoscopic/uclop@v1.1.0/mod/main.go:159 +0x262
main.main()
	ios_remote_provider/main.go:20 +0x325

**Comment by nanoscopic** [comment]
This is saying that the provider is unable to contact ControlFloor ( the server ) at the default URL ( when trying to connect the WebSocket ).

Have you first run `provider/main register` before running `provider/main run` ? If you don't first register the provider it will not be able to authenticate and then connect.

Also, ControlFloor is running already? ( `controlfloor/main run` )

**Comment by kristeedev** [comment]
Yes, controlfloor is already running.
On running provider/main register, I get this runtime error:

`panic: runtime error: index out of range [48] with length 48

goroutine 1 [running]:
github.com/nanoscopic/ujsonin/mod.Parse(0xc000132000, 0x30, 0x200, 0x30, 0x200, 0x0, 0x0)
	go/pkg/mod/github.com/nanoscopic/ujsonin@v1.13.0/mod/ujsonin.go:369 +0x1f3f
main.doregister(0xc0000c03c0, 0x0, 0x0)
	ios_remote_provider/controlfloor.go:415 +0x559
main.runRegister(0xc000096230)
	ios_remote_provider/main.go:46 +0x39
github.com/nanoscopic/uclop/mod.(*Cmd).Run(...)
	go/pkg/mod/github.com/nanoscopic/uclop@v1.1.0/mod/main.go:164
github.com/nanoscopic/uclop/mod.(*Uclop).Run(0xc000117e50)
	go/pkg/mod/github.com/nanoscopic/uclop@v1.1.0/mod/main.go:159 +0x262
main.main()
	ios_remote_provider/main.go:20 +0x325`

**Comment by nanoscopic** [comment]
This error essentially means "invalid JSON"; the JSON in question being what is returned by the register function. Whatever was returned was an error and not actually JSON.

There are two bugs/issues visible due to this:

1. The JSON parser I wrote gives unclear error messages when non-JSON is fed into it. This should be handled better so that it is more clear that this has happened. I am ( as of yesterday ) already making other improvements to the JSON parser; I will make this change also as it has been needed for a while.

2. The specific error with the registration here should be output as something other than a 200 response code, so that the code within Provider that makes the call knows it is not a JSON response. This code can/should/will be improved. With this improvement the first issue would never occur, but both should be made anyway.

**Comment by kristeedev** [comment]
Thanks @nanoscopic

**Comment by nanoscopic** [comment]
Has this particular error been fixed by the latest round of changes?

**Comment by kristeedev** [comment]
Tested this with new build. This is fixed.
