### ISSUE TITLE
iPhone 12 mini is displayed much more than full screen

### ISSUE THREAD

**Issue by Slavaleriya** [nanoscopic/ios_remote_provider#38]
Hi! Please tell me what could be the problem. iPhone12 mini is displayed much larger than the browser window, that is, you need to scroll up / down to see the top / bottom of the device screen. 
iPhone7 and iPhoneSE2020 do not have this problem

**Comment by nanoscopic** [comment]
This is "normal" / currently intended. It is also, of course, a bad UI design.

This is a result of just dividing the full screen resolution by two to determine what size to display in browser. For the moment you can simply zoom out, but that makes all the other UI elements smaller and misaligned.

This will be fixed soon in that the screen resolution will be maxed at something reasonable rather than using the poor temporary solution which is in place currently ( divide by two )

**Comment by nanoscopic** [comment]
The styling has been changed to limit vertical resolution to 1000 pixels. Also, an option to configure this amount has been added to ControlFloor config.json file.
