### ISSUE TITLE
After 300 or so actions, WDA hangs due to FD exhaustion

### ISSUE THREAD

**Issue by sai-tirunagiri** [nanoscopic/ios_remote_provider#39]
Hi,

This might be a duplicate of #20 but would like to keep this separate.

**Steps to reproduce:**
1 - Open notes
2 - start intense typing
3 - as we type, you will notice that nothing gets typed on the screen.

**Expected**
Even though wda restarts, it should again start from the notes app and should let me continue typing.

**Actual**
Goes back to the settings screen, and sometimes it just freezes.

**logs**
wda.log - https://gist.github.com/sai-tirunagiri/9cc3132b0a8538ea2b5f5cf4e42cf003
provider.log - https://gist.github.com/sai-tirunagiri/5125cf11b81f3159a4681dc4c4d61669

Thanks.

**Comment by nanoscopic** [comment]
As said on the other copy of this same issue, ( I agree this is a different issue though and should be separate ), this is due to lack of reuse of the http connection. Will fix.

**Comment by nanoscopic** [comment]
I investigated this and altered the code to reuse the http connection. It appears that WebDriverAgent doesn't support reusing the same connection so it still makes a new connection every time and still runs out of file descriptors quickly. Worse, even after the used up ones should have timed out it is still stuck in a broken state.

The most reasonable way I see to fix this issue is to alter WebDriverAgent to support a persistent WebSocket connection for running commands to avoid the constant repeated connections.

Unfortunately the current WDA maintainer, Appium, stripped out all the WebSocket support from CocoaHTTPServer, so I will need to add the support back in.

Essentially this is a non-trivial issue to fix...

**Comment by nanoscopic** [comment]
The latest updates address this by altering WDA to use NNG instead of HTTP.
